MODEL:
  NUM_CLASSES: 21
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("voc_2007_trainval", )
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 60000
  LR_STEPS: [40000, 50000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-3

OUTPUT_DIR: 'outputs/vgg_ssd300_voc07'
